baseURL = "https://infallible-brahmagupta-b5b27c.netlify.app/"
languageCode = "en-us"
title = "Ann Is Awesome"

theme = "kross"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "css/custom.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#41228e"
# contact info
phone = "+xxx xxx xxx"
email = "email@email.com"
address = "12345 street, USA"
# meta description
author = "ME"
description = "This is meta description"



# social site
[[params.social]]
icon = "ti-facebook"
URL = "#"

[[params.social]]
icon = "ti-instagram"
URL = "#"

[[params.social]]
icon = "ti-twitter-alt"
URL = "#"

